server:
  port: 8080

database:
  dbname: "feedback"
  dbhost: "localhost"
  dbsslmode: "disable"
  dbuser: "r.kuzmenko"
  dbpassword: "123123"
  dbport: 5432

parser:
  base_url: "https://api.delivery-club.ru/api1.2"
  limit: 1000
  chain_id: 28720